export const GET_DATA_FOR_DASHBOARD_REQUEST = 'GET_DATA_FOR_DASHBOARD_REQUEST'
export const GET_DATA_FOR_DASHBOARD_SUCCESS = 'GET_DATA_FOR_DASHBOARD_SUCCESS'
export const GET_DATA_FOR_DASHBOARD_ERROR = 'GET_DATA_FOR_DASHBOARD_ERROR'
