export const PUCHASE_CREATE_REQUEST = 'PUCHASE_CREATE_REQUEST'
export const PUCHASE_CREATE_SUCCESS = 'PUCHASE_CREATE_SUCCESS'
export const PUCHASE_CREATE_FAIL = 'PUCHASE_CREATE_FAIL'

export const PUCHASE_LIST_REQUEST = 'PUCHASE_LIST_REQUEST'
export const PUCHASE_LIST_SUCCESS = 'PUCHASE_LIST_SUCCESS'
export const PUCHASE_LIST_FAIL = 'PUCHASE_LIST_FAIL'

export const PUCHASE_DELETE_REQUEST = 'PUCHASE_DELETE_REQUEST'
export const PUCHASE_DELETE_SUCCESS = 'PUCHASE_DELETE_SUCCESS'
export const PUCHASE_DELETE_FAIL = 'PUCHASE_DELETE_FAIL'

export const PUCHASE_UPDATE_REQUEST = 'PUCHASE_UPDATE_REQUEST'
export const PUCHASE_UPDATE_SUCCESS = 'PUCHASE_UPDATE_SUCCESS'
export const PUCHASE_UPDATE_FAIL = 'PUCHASE_UPDATE_FAIL'

export const ADD_REMOVE_STOCK_REQUEST = 'ADD_REMOVE_STOCK_REQUEST'
export const ADD_REMOVE_STOCK_SUCCESS = 'ADD_REMOVE_STOCK_SUCCESS'
export const ADD_REMOVE_STOCK_FAIL = 'ADD_REMOVE_STOCK_FAIL'

export const ADD_SALE_REQUEST = 'ADD_SALE_REQUEST'
export const ADD_SALE_SUCCESS = 'ADD_SALE_SUCCESS'
export const ADD_SALE_FAIL = 'ADD_SALE_FAIL'