export const PURCHASE_LIST_REQUEST = 'PURCHASE_LIST_REQUEST'
export const PURCHASE_LIST_SUCCESS = 'PURCHASE_LIST_SUCCESS'
export const PURCHASE_LIST_FAIL = 'PURCHASE_LIST_FAIL'

export const PURCHASE_CREATE_REQUEST = 'PURCHASE_CREATE_REQUEST'
export const PURCHASE_CREATE_SUCCESS = 'PURCHASE_CREATE_SUCCESS'
export const PURCHASE_CREATE_FAIL = 'PURCHASE_CREATE_FAIL'

export const PURCHASE_UPDATE_REQUEST = 'PURCHASE_UPDATE_REQUEST'
export const PURCHASE_UPDATE_SUCCESS = 'PURCHASE_UPDATE_SUCCESS'
export const PURCHASE_UPDATE_FAIL = 'PURCHASE_UPDATE_FAIL'

export const PURCHASE_DELETE_REQUEST = 'PURCHASE_DELETE_REQUEST'
export const PURCHASE_DELETE_SUCCESS = 'PURCHASE_DELETE_SUCCESS'
export const PURCHASE_DELETE_FAIL = 'PURCHASE_DELETE_FAIL'

export const PURCHASE_DETAILS_REQUEST = 'PURCHASE_DETAILS_REQUEST'
export const PURCHASE_DETAILS_SUCCESS = 'PURCHASE_DETAILS_SUCCESS'
export const PURCHASE_DETAILS_FAIL = 'PURCHASE_DETAILS_FAIL'