export const SUPPLY_LIST_REQUEST = 'SUPPLY_LIST_REQUEST'
export const SUPPLY_LIST_SUCCESS = 'SUPPLY_LIST_SUCCESS'
export const SUPPLY_LIST_FAIL = 'SUPPLY_LIST_FAIL'

export const SUPPLY_CREATE_REQUEST = 'SUPPLY_CREATE_REQUEST'
export const SUPPLY_CREATE_SUCCESS = 'SUPPLY_CREATE_SUCCESS'
export const SUPPLY_CREATE_FAIL = 'SUPPLY_CREATE_FAIL'

export const SUPPLY_UPDATE_REQUEST = 'SUPPLY_UPDATE_REQUEST'
export const SUPPLY_UPDATE_SUCCESS = 'SUPPLY_UPDATE_SUCCESS'
export const SUPPLY_UPDATE_FAIL = 'SUPPLY_UPDATE_FAIL'

export const SUPPLY_DELETE_REQUEST = 'SUPPLY_DELETE_REQUEST'
export const SUPPLY_DELETE_SUCCESS = 'SUPPLY_DELETE_SUCCESS'
export const SUPPLY_DELETE_FAIL = 'SUPPLY_DELETE_FAIL'