//Courses
export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST';
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS';
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL';

export const COURSE_DETAILS_REQUEST = 'COURSE_DETAILS_REQUEST';
export const COURSE_DETAILS_SUCCESS = 'COURSE_DETAILS_SUCCESS';
export const COURSE_DETAILS_FAIL = 'COURSE_DETAILS_FAIL';

export const COURSE_DELETE_REQUEST = 'COURSE_DELETE_REQUEST';
export const COURSE_DELETE_SUCCESS = 'COURSE_DELETE_SUCCESS';
export const COURSE_DELETE_FAIL = 'COURSE_DELETE_FAIL';
export const COURSE_DELETE_RESET = 'COURSE_DELETE_RESET';

export const COURSE_UPDATE_REQUEST = 'COURSE_UPDATE_REQUEST';
export const COURSE_UPDATE_SUCCESS = 'COURSE_UPDATE_SUCCESS';
export const COURSE_UPDATE_FAIL = 'COURSE_UPDATE_FAIL';
export const COURSE_UPDATE_RESET = 'COURSE_UPDATE_RESET';

export const COURSE_CREATE_REQUEST = 'COURSE_CREATE_REQUEST';
export const COURSE_CREATE_SUCCESS = 'COURSE_CREATE_SUCCESS';
export const COURSE_CREATE_FAIL = 'COURSE_CREATE_FAIL';
export const COURSE_CREATE_RESET = 'COURSE_CREATE_RESET';

//Sections
export const SECTION_LIST_REQUEST = 'SECTION_LIST_REQUEST';
export const SECTION_LIST_SUCCESS = 'SECTION_LIST_SUCCESS';
export const SECTION_LIST_FAIL = 'SECTION_LIST_FAIL';

export const SECTION_CREATE_REQUEST = 'SECTION_CREATE_REQUEST';
export const SECTION_CREATE_SUCCESS = 'SECTION_CREATE_SUCCESS';
export const SECTION_CREATE_FAIL = 'SECTION_CREATE_FAIL';
export const SECTION_CREATE_RESET = 'SECTION_CREATE_RESET';

export const SECTION_DELETE_REQUEST = 'SECTION_DELETE_REQUEST';
export const SECTION_DELETE_SUCCESS = 'SECTION_DELETE_SUCCESS';
export const SECTION_DELETE_FAIL = 'SECTION_DELETE_FAIL';
export const SECTION_DELETE_RESET = 'SECTION_DELETE_RESET';

export const SECTION_UPDATE_REQUEST = 'SECTION_UPDATE_REQUEST';
export const SECTION_UPDATE_SUCCESS = 'SECTION_UPDATE_SUCCESS';
export const SECTION_UPDATE_FAIL = 'SECTION_UPDATE_FAIL';
export const SECTION_UPDATE_RESET = 'SECTION_UPDATE_RESET';

//Videos
export const VIDEO_LIST_REQUEST = 'VIDEO_LIST_REQUEST';
export const VIDEO_LIST_SUCCESS = 'VIDEO_LIST_SUCCESS';
export const VIDEO_LIST_FAIL = 'VIDEO_LIST_FAIL';

export const VIDEO_CREATE_REQUEST = 'VIDEO_CREATE_REQUEST';
export const VIDEO_CREATE_SUCCESS = 'VIDEO_CREATE_SUCCESS';
export const VIDEO_CREATE_FAIL = 'VIDEO_CREATE_FAIL';
export const VIDEO_CREATE_RESET = 'VIDEO_CREATE_RESET';

export const VIDEO_DELETE_REQUEST = 'VIDEO_DELETE_REQUEST';
export const VIDEO_DELETE_SUCCESS = 'VIDEO_DELETE_SUCCESS';
export const VIDEO_DELETE_FAIL = 'VIDEO_DELETE_FAIL';
export const VIDEO_DELETE_RESET = 'VIDEO_DELETE_RESET';

export const VIDEO_UPDATE_REQUEST = 'VIDEO_UPDATE_REQUEST';
export const VIDEO_UPDATE_SUCCESS = 'VIDEO_UPDATE_SUCCESS';
export const VIDEO_UPDATE_FAIL = 'VIDEO_UPDATE_FAIL';
export const VIDEO_UPDATE_RESET = 'VIDEO_UPDATE_RESET';
