export const COUSRE_ENROLL_REQUEST = 'COUSRE_ENROLL_REQUEST';
export const COUSRE_ENROLL_SUCCESS = 'COUSRE_ENROLL_SUCCESS';
export const COUSRE_ENROLL_FAIL = 'COUSRE_ENROLL_FAIL';
export const COUSRE_ENROLL_RESET = 'COUSRE_ENROLL_RESET';
