export const NAVBAR_TYPE_REQUEST = 'NAVBAR_TYPE_REQUEST';
export const NAVBAR_TYPE_SUCCESS = 'NAVBAR_TYPE_SUCCESS';
export const NAVBAR_TYPE_FAIL = 'NAVBAR_TYPE_FAIL';

export const LOADER_TOP_TRUE = 'LOADER_TOP_TRUE';
export const LOADER_TOP_FALSE = 'LOADER_TOP_FALSE';
