

export const GET_DETAIL_REQUEST = 'GET_DETAIL_REQUEST'
export const GET_DETAIL_SUCCESS = 'GET_DETAIL_SUCCESS'
export const GET_DETAIL_FAIL = 'GET_DETAIL_FAIL'



export const GET_DETAIL_BY_CONTENT_ID_REQUEST = 'GET_DETAIL_BY_CONTENT_ID_REQUEST'
export const GET_DETAIL_BY_CONTENT_ID_SUCCESS = 'GET_DETAIL_BY_CONTENT_ID_SUCCESS'
export const GET_DETAIL_BY_CONTENT_ID_FAIL = 'GET_DETAIL_BY_CONTENT_ID_FAIL'

export const CREATE_DETAIL_REQUEST = 'CREATE_DETAIL_REQUEST'
export const CREATE_DETAIL_SUCCESS = 'CREATE_DETAIL_SUCCESS'
export const CREATE_DETAIL_FAIL = 'CREATE_DETAIL_FAIL'


export const DELETE_DETAIL_REQUEST = 'DELETE_DETAIL_REQUEST'
export const DELETE_DETAIL_SUCCESS = 'DELETE_DETAIL_SUCCESS'
export const DELETE_DETAIL_FAIL = 'DELETE_DETAIL_FAIL'

export const GET_ONE_DETAIL_REQUEST = 'GET_ONE_DETAIL_REQUEST'
export const GET_ONE_DETAIL_SUCCESS = 'GET_ONE_DETAIL_SUCCESS'
export const GET_ONE_DETAIL_FAIL = 'GET_ONE_DETAIL_FAIL'

export const UPDATE_DETAIL_REQUEST = 'UPDATE_DETAIL_REQUEST'
export const UPDATE_DETAIL_SUCCESS = 'UPDATE_DETAIL_SUCCESS'
export const UPDATE_DETAIL_FAIL = 'UPDATE_DETAIL_FAIL'










