export const GET_CONTENT_REQUEST = 'GET_CONTENT_REQUEST'
export const GET_CONTENT_SUCCESS = 'GET_CONTENT_SUCCESS'
export const GET_CONTENT_FAIL = 'GET_CONTENT_FAIL'


export const GET_CONTENT_BY_LANG_REQUEST = 'GET_CONTENT_BY_LANG_REQUEST'
export const GET_CONTENT_BY_LANG_SUCCESS = 'GET_CONTENT_BY_LANG_SUCCESS'
export const GET_CONTENT_BY_LANG_FAIL = 'GET_CONTENT_BY_LANG_FAIL'


export const ADD_CONTENT_REQUEST = 'ADD_CONTENT_REQUEST'
export const ADD_CONTENT_SUCCESS = 'ADD_CONTENT_SUCCESS'
export const ADD_CONTENT_FAIL = 'ADD_CONTENT_FAIL'

export const DELETE_CONTENT_REQUEST = 'DELETE_CONTENT_REQUEST'
export const DELETE_CONTENT_SUCCESS = 'DELETE_CONTENT_SUCCESS'
export const DELETE_CONTENT_FAIL = 'DELETE_CONTENT_FAIL'

export const UPDATE_CONTENT_REQUEST = 'UPDATE_CONTENT_REQUEST'
export const UPDATE_CONTENT_SUCCESS = 'UPDATE_CONTENT_SUCCESS'
export const UPDATE_CONTENT_FAIL = 'UPDATE_CONTENT_FAIL'

export const CREATE_CONTENT_REQUEST = 'CREATE_CONTENT_REQUEST'
export const CREATE_CONTENT_SUCCESS = 'CREATE_CONTENT_SUCCESS'
export const CREATE_CONTENT_FAIL = 'CREATE_CONTENT_FAIL'