export const GET_LANGUAGE_REQUEST = 'GET_LANGUAGE_REQUEST'
export const GET_LANGUAGE_SUCCESS = 'GET_LANGUAGE_SUCCESS'
export const GET_LANGUAGE_FAIL = 'GET_LANGUAGE_FAIL'

export const GET_ONE_LANGUAGE_REQUEST = 'GET_ONE_LANGUAGE_REQUEST'
export const GET_ONE_LANGUAGE_SUCCESS = 'GET_ONE_LANGUAGE_SUCCESS'
export const GET_ONE_LANGUAGE_FAIL = 'GET_ONE_LANGUAGE_FAIL'

export const ADD_LANGUAGE_REQUEST = 'ADD_LANGUAGE_REQUEST'
export const ADD_LANGUAGE_SUCCESS = 'ADD_LANGUAGE_SUCCESS'
export const ADD_LANGUAGE_FAIL = 'ADD_LANGUAGE_FAIL'

export const DELETE_LANGUAGE_REQUEST = 'DELETE_LANGUAGE_REQUEST'
export const DELETE_LANGUAGE_SUCCESS = 'DELETE_LANGUAGE_SUCCESS'
export const DELETE_LANGUAGE_FAIL = 'DELETE_LANGUAGE_FAIL'

export const UPDATE_LANGUAGE_REQUEST = 'UPDATE_LANGUAGE_REQUEST'
export const UPDATE_LANGUAGE_SUCCESS = 'UPDATE_LANGUAGE_SUCCESS'
export const UPDATE_LANGUAGE_FAIL = 'UPDATE_LANGUAGE_FAIL'