export const COUSRE_ENROLL_REQUEST = 'COUSRE_ENROLL_REQUEST';
export const COUSRE_ENROLL_SUCCESS = 'COUSRE_ENROLL_SUCCESS';
export const COUSRE_ENROLL_FAIL = 'COUSRE_ENROLL_FAIL';
export const COUSRE_ENROLL_RESET = 'COUSRE_ENROLL_RESET';

export const USER_ENROLL_COURSE_REQUEST = 'USER_ENROLL_COURSE_REQUEST';
export const USER_ENROLL_COURSE_SUCCESS = 'USER_ENROLL_COURSE_SUCCESS';
export const USER_ENROLL_COURSE_RESET = 'USER_ENROLL_COURSE_RESET';
export const USER_ENROLL_COURSE_FAIL = 'USER_ENROLL_COURSE_FAIL';

export const USER_ENROLL_CREATE_REQUEST = 'USER_ENROLL_CREATE_REQUEST';
export const USER_ENROLL_CREATE_SUCCESS = 'USER_ENROLL_CREATE_SUCCESS';
export const USER_ENROLL_CREATE_RESET = 'USER_ENROLL_CREATE_RESET';
export const USER_ENROLL_CREATE_FAIL = 'USER_ENROLL_CREATE_FAIL';
