export const COUSRE_ENROLL_REQUEST = 'COUSRE_ENROLL_REQUEST';
export const COUSRE_ENROLL_SUCCESS = 'COUSRE_ENROLL_SUCCESS';
export const COUSRE_ENROLL_FAIL = 'COUSRE_ENROLL_FAIL';
export const COUSRE_ENROLL_RESET = 'COUSRE_ENROLL_RESET';

export const USER_ENROLL_COURSE_REQUEST = 'USER_ENROLL_COURSE_REQUEST';
export const USER_ENROLL_COURSE_SUCCESS = 'USER_ENROLL_COURSE_SUCCESS';
export const USER_ENROLL_COURSE_RESET = 'USER_ENROLL_COURSE_RESET';
export const USER_ENROLL_COURSE_FAIL = 'USER_ENROLL_COURSE_FAIL';

export const USER_ENROLL_CREATE_REQUEST = 'USER_ENROLL_CREATE_REQUEST';
export const USER_ENROLL_CREATE_SUCCESS = 'USER_ENROLL_CREATE_SUCCESS';
export const USER_ENROLL_CREATE_RESET = 'USER_ENROLL_CREATE_RESET';
export const USER_ENROLL_CREATE_FAIL = 'USER_ENROLL_CREATE_FAIL';

export const USER_ENROLL_DELETE_REQUEST = 'USER_ENROLL_DELETE_REQUEST';
export const USER_ENROLL_DELETE_SUCCESS = 'USER_ENROLL_DELETE_SUCCESS';
export const USER_ENROLL_DELETE_RESET = 'USER_ENROLL_DELETE_RESET';
export const USER_ENROLL_DELETE_FAIL = 'USER_ENROLL_DELETE_FAIL';

export const GET_ENROLL_SECTION_REQUEST = 'GET_ENROLL_SECTION_REQUEST';
export const GET_ENROLL_SECTION_SUCCESS = 'GET_ENROLL_SECTION_SUCCESS';
export const GET_ENROLL_SECTION_RESET = 'GET_ENROLL_SECTION_RESET';
export const GET_ENROLL_SECTION_FAIL = 'GET_ENROLL_SECTION_FAIL';

export const GET_ENROLL_VIDEO_REQUEST = 'GET_ENROLL_VIDEO_REQUEST';
export const GET_ENROLL_VIDEO_SUCCESS = 'GET_ENROLL_VIDEO_SUCCESS';
export const GET_ENROLL_VIDEO_RESET = 'GET_ENROLL_VIDEO_RESET';
export const GET_ENROLL_VIDEO_FAIL = 'GET_ENROLL_VIDEO_FAIL';

export const ADD_ENROLL_VIDEO_REQUEST = 'ADD_ENROLL_VIDEO_REQUEST';
export const ADD_ENROLL_VIDEO_SUCCESS = 'ADD_ENROLL_VIDEO_SUCCESS';
export const ADD_ENROLL_VIDEO_RESET = 'ADD_ENROLL_VIDEO_RESET';
export const ADD_ENROLL_VIDEO_FAIL = 'ADD_ENROLL_VIDEO_FAIL';

export const GET_ENROLL_DETAIL_REQUEST = 'GET_ENROLL_DETAIL_REQUEST';
export const GET_ENROLL_DETAIL_SUCCESS = 'GET_ENROLL_DETAIL_SUCCESS';
export const GET_ENROLL_DETAIL_RESET = 'GET_ENROLL_DETAIL_RESET';
export const GET_ENROLL_DETAIL_FAIL = 'GET_ENROLL_DETAIL_FAIL';

export const GET_REQ_ENROLL_REQ = 'GET_REQ_ENROLL_REQ';
export const GET_REQ_ENROLL_SUC = 'GET_REQ_ENROLL_SUC';
export const GET_REQ_ENROLL_FAIL = 'GET_REQ_ENROLL_FAIL';
export const GET_REQ_ENROLL_RESET = 'GET_REQ_ENROLL_RESET';

export const DELETE_REQ_ENROLL_REQ = 'DELETE_REQ_ENROLL_REQ';
export const DELETE_REQ_ENROLL_SUC = 'DELETE_REQ_ENROLL_SUC';
export const DELETE_REQ_ENROLL_FAIL = 'DELETE_REQ_ENROLL_FAIL';
export const DELETE_REQ_ENROLL_RESET = 'DELETE_REQ_ENROLL_RESET';

export const CREATE_REQ_ENROLL_SUCCESS = 'CREATE_REQ_ENROLL_SUCCESS';
